version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: expense_tracker_postgres
    restart: always
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"  # проброс порта хосту
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
